table miboml
	lineageTag: 74cd156c-41e8-44a8-bacd-671dae649f65

	measure MakeQty =
			
			DIVIDE(
			    SUM(miboml[OH]),
			    SUM(miboml[nqty])
			)
		formatString: #,0
		lineageTag: 262339ae-d5c1-4a6d-8ad4-a751fd3c6007

		annotation PBI_FormatHint = {"isDecimal":true}

	measure MakeNegative = ```
			IF([MakeQty] <= 0, 1, 0)
			
			```
		formatString: 0
		lineageTag: 8ce480eb-1979-496e-9f73-cf58e57d916d

	column citemno
		dataType: string
		lineageTag: b34b4b39-5d5e-400a-8caf-e7093c4854e0
		summarizeBy: none
		sourceColumn: citemno

		annotation SummarizationSetBy = Automatic

	column ccompno
		dataType: string
		lineageTag: 7e3182e4-4a78-48ba-bfa3-bfbf8246fb31
		summarizeBy: none
		sourceColumn: ccompno

		annotation SummarizationSetBy = Automatic

	column cdescript
		dataType: string
		lineageTag: 7259d4f3-4f58-4680-9be8-85cf4f40d3b9
		summarizeBy: none
		sourceColumn: cdescript

		annotation SummarizationSetBy = Automatic

	column cmeasure
		dataType: string
		lineageTag: 728afd19-3c14-4f26-9706-d9a66cc518ba
		summarizeBy: none
		sourceColumn: cmeasure

		annotation SummarizationSetBy = Automatic

	column ctype
		dataType: string
		lineageTag: d51b22c4-05bf-4393-a4ea-9ec0ccb4644a
		summarizeBy: none
		sourceColumn: ctype

		annotation SummarizationSetBy = Automatic

	column dcreate
		dataType: dateTime
		formatString: General Date
		lineageTag: ee79d9ce-89bb-4efa-abd2-26ea120ff6df
		summarizeBy: none
		sourceColumn: dcreate

		variation Variation
			isDefault
			relationship: 995e9c37-639d-4d8b-8120-c69145346ff5
			defaultHierarchy: LocalDateTable_644d37a0-8df5-4c3f-98f7-f49f0ec79cc3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column nqtydec
		dataType: int64
		formatString: 0
		lineageTag: 72357f04-9a13-4f94-a376-a43c83354440
		summarizeBy: sum
		sourceColumn: nqtydec

		annotation SummarizationSetBy = Automatic

	column nstep
		dataType: int64
		formatString: 0
		lineageTag: ebd4dee2-30d0-4620-8e57-9b9af5c6579e
		summarizeBy: sum
		sourceColumn: nstep

		annotation SummarizationSetBy = Automatic

	column nuptime
		dataType: double
		lineageTag: 5a94ec93-9549-4b7f-bf9a-26311b4b4966
		summarizeBy: sum
		sourceColumn: nuptime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ndntime
		dataType: double
		lineageTag: 1e7f2f89-6dc5-42b9-a737-316092af44be
		summarizeBy: sum
		sourceColumn: ndntime

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column nqty
		dataType: double
		formatString: #,0
		lineageTag: fe03bb9e-5b30-41d6-8705-fe86f8e2fdc6
		summarizeBy: sum
		sourceColumn: nqty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column nrate
		dataType: double
		lineageTag: 391509af-1481-44ac-8643-891ca04ee9f6
		summarizeBy: sum
		sourceColumn: nrate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ncnvqty
		dataType: double
		lineageTag: 73185ad5-c35e-4f97-808a-dcf63f27dc58
		summarizeBy: sum
		sourceColumn: ncnvqty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cspeccode1
		dataType: string
		lineageTag: 9a057497-6ac0-454c-a060-1e034b3b8b7e
		summarizeBy: none
		sourceColumn: cspeccode1

		annotation SummarizationSetBy = Automatic

	column cspeccode2
		dataType: string
		lineageTag: b64fb1bb-3591-43c3-8058-445d7372a0db
		summarizeBy: none
		sourceColumn: cspeccode2

		annotation SummarizationSetBy = Automatic

	column ccspecode1
		dataType: string
		lineageTag: 49d8be32-53bf-49d6-98a3-22462bfb520b
		summarizeBy: none
		sourceColumn: ccspecode1

		annotation SummarizationSetBy = Automatic

	column ccspecode2
		dataType: string
		lineageTag: 8ee88384-9e1a-4778-976e-f32a15381cd2
		summarizeBy: none
		sourceColumn: ccspecode2

		annotation SummarizationSetBy = Automatic

	column cuid
		dataType: string
		lineageTag: 2d1d4daa-a520-4137-8b2c-3d0ad5da138c
		summarizeBy: none
		sourceColumn: cuid

		annotation SummarizationSetBy = Automatic

	column OH =
			
			SUMX(
			    RELATEDTABLE(
			        icibin_2),
			        icibin_2[nonhand]
			)
		formatString: #,0
		lineageTag: e1e25d1f-4c29-427b-8710-07320b5f314a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column IsTarget = ```
			
			VAR Prefix =
			    LEFT ( miboml[cdescript], 
			        FIND ( " ", miboml[cdescript] & " ", 1 ) - 1
			    )
			RETURN
			    IF (
			        Prefix IN { "FLANGE", "U-RING", "L-RING", "Z-RING", "RETAINER", "COUPLING", "THREADED COUPLING" },
			        TRUE (),
			        FALSE ()
			    )
			
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3b7a70a1-68bd-41e4-9053-67cf09904ac4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Due = ```
			
			VAR OpenPOs =
			    FILTER(
			        RELATEDTABLE(poptrs),
			        ISBLANK(poptrs[LastRecDate]) && poptrs[OpenQty] > 0
			    )
			RETURN
			    MINX(OpenPOs, poptrs[drequest])
			
			```
		formatString: m/d/yy
		lineageTag: 7026d88d-6be0-4f33-a8d6-41b0209e73de
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 6a6cb04d-660e-487b-af3b-45cc1c28830d
			defaultHierarchy: LocalDateTable_38eb52ab-8749-42c0-b297-78cc8583f2cb.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column IsNegative = IF([MakeQty] <= 0, 1, 0)
		formatString: 0
		lineageTag: 97757369-7d8b-4246-9ca0-a50099dabd13
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition miboml = m
		mode: import
		source =
				let
				    Source = Sql.Database("keltec-sql:1433", "keltec", [Query="SELECT * FROM dbo.miboml"])
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

